<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ISAMS — Forgot Password</title>
<link href="https://fonts.googleapis.com/css2?family=Sora:wght@700;800&family=DM+Sans:wght@400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
<style>*,*::before,*::after{box-sizing:border-box;margin:0;padding:0;}body{font-family:'DM Sans',sans-serif;min-height:100vh;display:flex;align-items:center;justify-content:center;background:linear-gradient(145deg,#0d3318,#1a6b2f,#2d9e4f);padding:20px;}.card{background:#fff;border-radius:18px;width:100%;max-width:420px;padding:36px;box-shadow:0 24px 64px rgba(0,0,0,.25);}.logo{display:flex;align-items:center;gap:9px;margin-bottom:20px;}.logo-icon{width:36px;height:36px;background:linear-gradient(135deg,#f0c020,#c9a010);border-radius:9px;display:flex;align-items:center;justify-content:center;font-size:15px;color:#0d3318;}.logo-name{font-family:'Sora',sans-serif;font-size:17px;font-weight:800;color:#1a6b2f;}h2{font-family:'Sora',sans-serif;font-size:20px;font-weight:700;color:#1a6b2f;margin-bottom:4px;}p{font-size:13px;color:#5a7a60;margin-bottom:20px;line-height:1.5;}.fg{margin-bottom:14px;}.fl{display:block;font-size:13px;font-weight:600;color:#1a2e1a;margin-bottom:5px;}.iw{position:relative;}.iw i{position:absolute;left:12px;top:50%;transform:translateY(-50%);color:#8ab898;font-size:13px;}.fc{width:100%;padding:10px 12px 10px 37px;border:1.5px solid #cde0d0;border-radius:9px;font-size:14px;font-family:inherit;}.fc:focus{outline:none;border-color:#2d9e4f;}.btn{width:100%;padding:12px;background:linear-gradient(135deg,#1a6b2f,#2d9e4f);color:#fff;border:none;border-radius:9px;font-size:15px;font-weight:700;cursor:pointer;font-family:'Sora',sans-serif;}.al-s{padding:11px 14px;background:#d0f0d8;border-left:4px solid #1a7a4a;border-radius:8px;color:#0d4a1e;font-size:13px;margin-bottom:14px;}.back{display:block;text-align:center;margin-top:16px;font-size:13px;color:#2d9e4f;text-decoration:none;}</style></head>
<body><div class="card"><div class="logo"><div class="logo-icon"><i class="fas fa-brain"></i></div><div class="logo-name">ISAMS</div></div>
<h2>Forgot Password</h2><p>Enter your registered email and we'll send a password reset link.</p>
@if(session('status'))<div class="al-s"><i class="fas fa-check-circle" style="margin-right:6px;"></i>{{ session('status') }}</div>@endif
<form method="POST" action="{{ route('password.email') }}">@csrf
<div class="fg"><label class="fl">Email Address</label><div class="iw"><i class="fas fa-envelope"></i><input type="email" name="email" class="fc" placeholder="your@isams.edu.ph" required value="{{ old('email') }}"></div></div>
<button type="submit" class="btn"><i class="fas fa-paper-plane" style="margin-right:6px;"></i>Send Reset Link</button></form>
<a href="{{ route('login') }}" class="back"><i class="fas fa-arrow-left" style="margin-right:4px;"></i>Back to Login</a>
</div></body></html>
