<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\{User,Student,Scholarship,ScholarshipApplication,Announcement};
class DatabaseSeeder extends Seeder {
    public function run(): void {
        User::create(['name'=>'Super Administrator','email'=>'superadmin@isams.edu.ph','password'=>Hash::make('password'),'role'=>'superadmin','department'=>'IT Administration','is_active'=>true]);
        User::create(['name'=>'Scholarship Administrator','email'=>'admin@isams.edu.ph','password'=>Hash::make('password'),'role'=>'admin','department'=>'Scholarship Office','is_active'=>true]);
        User::create(['name'=>'Dr. Maria Rivera','email'=>'officer@isams.edu.ph','password'=>Hash::make('password'),'role'=>'officer','department'=>'Scholarship Office','is_active'=>true]);
        $studentUser=User::create(['name'=>'Maria Santos','email'=>'student@isams.edu.ph','password'=>Hash::make('password'),'role'=>'student','is_active'=>true]);
        $rows=[['Maria','Santos','2024-0001','BS Computer Science','3rd Year',1.50,'Regular'],['Juan','Dela Cruz','2024-0002','BS Education','2nd Year',1.75,'Regular'],['Ana','Reyes','2024-0003','BS Nursing','4th Year',1.25,'Regular'],['Carlos','Mendoza','2024-0004','BS Engineering','1st Year',2.10,'Irregular'],['Rosa','Garcia','2024-0005','BS Business Administration','3rd Year',1.60,'Regular'],['Pedro','Lim','2024-0006','AB Communication','2nd Year',1.80,'Regular'],['Elena','Cruz','2024-0007','BS Computer Science','4th Year',1.40,'Regular'],['Tony','Bautista','2024-0008','BS Nursing','3rd Year',2.80,'Irregular'],['Liza','Torres','2024-0009','BS Accountancy','2nd Year',1.60,'Regular'],['Ben','Ramos','2024-0010','BS Computer Science','3rd Year',1.90,'Regular'],['Grace','Tan','2024-0011','BS Computer Science','2nd Year',1.45,'Regular'],['Felix','Uy','2024-0012','BS Engineering','1st Year',3.10,'Irregular']];
        $students=[];
        foreach ($rows as $i=>$r) {
            $u=($i===0)?$studentUser:User::create(['name'=>$r[0].' '.$r[1],'email'=>strtolower($r[0].'.'.str_replace(' ','_',$r[1]).$i.'@isams.edu.ph'),'password'=>Hash::make('password'),'role'=>'student','is_active'=>true]);
            $students[]=Student::create(['user_id'=>$u->id,'first_name'=>$r[0],'last_name'=>$r[1],'student_id'=>$r[2],'course'=>$r[3],'year_level'=>$r[4],'gwa'=>$r[5],'enrollment_type'=>$r[6],'academic_year'=>'2023-2024','semester'=>'2nd','status'=>'Active','email'=>strtolower($r[0].'.'.$r[1].'@email.com'),'contact_number'=>'0917'.rand(1000000,9999999),'sex'=>$i%2===0?'Female':'Male']);
        }
        $schRows=[['CHED Scholarship','Government','Full Tuition + ₱2,000/mo stipend',250,['gwa_max'=>1.75,'enrollment'=>'Regular','income_max'=>400000,'no_failing'=>true,'no_discipline'=>true]],['TES - Tertiary Education Subsidy','Government','₱40,000/year',180,['enrollment'=>'Regular','no_failing'=>true,'income_max'=>500000]],['DOST-SEI Scholarship','Government','Full tuition + ₱7,000/mo + allowances',45,['gwa_max'=>1.75,'no_failing'=>true,'no_discipline'=>true]],['Presidential Scholarship','Institutional','Full Tuition Coverage',30,['gwa_max'=>1.25,'no_failing'=>true,'no_discipline'=>true]],['Athletic Scholarship','Institutional','50% Tuition Discount',60,['gwa_max'=>2.50]],['SM College Scholarship','Private','Full Tuition + ₱5,000/mo',25,['gwa_max'=>1.75,'no_failing'=>true]],['Gokongwei Foundation','Private','₱50,000/year',20,['gwa_max'=>1.75,'income_max'=>400000]],['Cultural Arts Grant','Institutional','25% Tuition Discount',22,['gwa_max'=>2.50]]];
        $scholarships=[];
        foreach ($schRows as $s) { $scholarships[]=Scholarship::create(['name'=>$s[0],'type'=>$s[1],'benefits'=>$s[2],'slots'=>$s[3],'status'=>'Active','ai_criteria'=>json_encode($s[4])]); }
        $apps=[[0,0,1.50,'Regular',false,false,'below_200',94,'Eligible','Renewal Ready','Approved','GWA 1.50 meets requirement. Regular enrollment. Income qualifies.'],[0,2,1.50,'Regular',false,false,'below_200',97,'Eligible','Renewal Ready','Approved','Top DOST qualifier. All criteria met.'],[0,1,1.50,'Regular',false,false,'below_200',83,'Eligible','Renewal Ready','Approved','All TES criteria met.'],[1,0,1.75,'Regular',false,false,'below_200',81,'Eligible','Renewal Ready','Pending','Meets GWA requirement. All clear.'],[2,2,1.25,'Regular',false,false,'below_200',97,'Eligible','Renewal Ready','Approved','Exceptional GWA 1.25. Top DOST qualifier.'],[3,0,2.10,'Irregular',false,false,'200_400',62,'For Review','Needs Requirements','For Review','GWA 2.10 exceeds max 1.75. Irregular enrollment.'],[4,3,1.40,'Regular',false,false,'below_200',88,'Eligible','Renewal Ready','Pending','Excellent GWA. Qualifies for Presidential.'],[5,4,1.80,'Regular',false,false,'200_400',45,'For Review','Needs Requirements','For Review','Missing varsity endorsement letter.'],[6,5,1.35,'Regular',false,false,'below_200',91,'Eligible','Renewal Ready','Approved','Strong GWA. All SM criteria met.'],[7,0,2.80,'Irregular',true,false,'above_400',22,'Not Eligible','Disqualified','Rejected','GWA 2.80 far above max 1.75. Has failing grades.'],[8,1,1.60,'Regular',false,false,'below_200',86,'Eligible','Renewal Ready','Pending','Meets all TES requirements.'],[9,6,1.90,'Regular',false,false,'200_400',68,'For Review','Needs Requirements','Pending','GWA slightly above max 1.75. Income borderline.'],[10,0,1.45,'Regular',false,false,'below_200',93,'Eligible','Renewal Ready','Pending','Strong qualifier. All documents required.'],[11,4,3.10,'Irregular',true,true,'above_400',15,'Not Eligible','Disqualified','Rejected','GWA 3.10. Failing grades. Active discipline case.']];
        foreach ($apps as $a) { ScholarshipApplication::create(['student_id'=>$students[$a[0]]->id,'scholarship_id'=>$scholarships[$a[1]]->id,'gwa'=>$a[2],'enrollment_type'=>$a[3],'has_failing'=>$a[4],'has_discipline'=>$a[5],'income_bracket'=>$a[6],'ai_score'=>$a[7],'ai_eligibility'=>$a[8],'ai_tag'=>$a[9],'status'=>$a[10],'ai_reasoning'=>$a[11],'ai_run_at'=>now()]); }
        $anns=[['CHED Scholarship Applications Now Open','Submit your application before May 30, 2024. Slots are limited.','Scholarship','High'],['DOST-SEI Renewal Requirements Due','All DOST-SEI scholars must submit renewal documents by May 15, 2024.','Renewal','High'],['Presidential Scholarship — Only 2 Slots Left!','Act fast! The Presidential Scholarship now only has 2 remaining slots.','Scholarship','Urgent'],['SM Scholarship Deadline Extended','SM Foundation extended the deadline to June 30, 2024.','Scholarship','Normal'],['ISAMS AI Engine Updated to v2.1','Improved eligibility detection accuracy of 98.4%.','System','Normal']];
        foreach ($anns as $a) { Announcement::create(['title'=>$a[0],'body'=>$a[1],'type'=>$a[2],'priority'=>$a[3],'user_id'=>2,'published_at'=>now()]); }
    }
}
