services:
  - type: web
    name: isams
    runtime: docker
    plan: free
    healthCheckPath: /login
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: ISAMS
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_TIMEZONE
        value: Asia/Manila
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-ap-northeast-2.pooler.supabase.com
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.lhcwxhzhqgccefyqqckr
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: "120"
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: MAIL_MAILER
        value: log
      - key: GROQ_API_KEY
        sync: false
