<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title><?php echo e($title); ?></title>
<style>
    body { font-family: Helvetica, Arial, sans-serif; font-size: 10px; color: #1a2e1a; }
    h1 { font-size: 17px; color: #1a6b2f; margin: 0 0 2px; }
    .sub { font-size: 9px; color: #5a7a60; margin-bottom: 12px; }
    .rule { border-bottom: 2px solid #1a6b2f; margin-bottom: 12px; }
    table { width: 100%; border-collapse: collapse; }
    th { background: #e8f5ec; color: #1a6b2f; font-size: 8.5px; text-transform: uppercase; letter-spacing: .5px; padding: 6px 7px; border: 1px solid #cde0d0; text-align: left; }
    td { padding: 5px 7px; border: 1px solid #dde8df; font-size: 9.5px; }
    tr:nth-child(even) td { background: #f6faf7; }
    .footer { margin-top: 14px; font-size: 8.5px; color: #5a7a60; }
</style>
</head>
<body>
<h1>ISAMS — <?php echo e($title); ?></h1>
<div class="sub">Saint Columban College &middot; Pagadian City &middot; Generated <?php echo e(now()->format('M d, Y h:i A')); ?> &middot; <?php echo e(count($rows)); ?> record(s)</div>
<div class="rule"></div>
<table>
    <thead><tr>
        <?php $__currentLoopData = $headings; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $h): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><th><?php echo e($h); ?></th><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
    </tr></thead>
    <tbody>
    <?php $__empty_1 = true; $__currentLoopData = $rows; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
        <tr><?php $__currentLoopData = $row; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $cell): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><td><?php echo e($cell); ?></td><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tr>
    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
        <tr><td colspan="<?php echo e(count($headings)); ?>" style="text-align:center;padding:16px;color:#5a7a60;">No records found.</td></tr>
    <?php endif; ?>
    </tbody>
</table>
<div class="footer">Generated by ISAMS — Integrated Student Affairs Management System</div>
</body>
</html>
<?php /**PATH C:\Users\Acer\Herd\isams\resources\views/admin/reports/pdf.blade.php ENDPATH**/ ?>