<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{{ $title }}</title>
<style>
    body { font-family: Helvetica, Arial, sans-serif; font-size: 10px; color: #1a2e1a; }
    h1 { font-size: 17px; color: #1a6b2f; margin: 0 0 2px; }
    .sub { font-size: 9px; color: #5a7a60; margin-bottom: 12px; }
    .rule { border-bottom: 2px solid #1a6b2f; margin-bottom: 12px; }
    table { width: 100%; border-collapse: collapse; }
    th { background: #e8f5ec; color: #1a6b2f; font-size: 8.5px; text-transform: uppercase; letter-spacing: .5px; padding: 6px 7px; border: 1px solid #cde0d0; text-align: left; }
    td { padding: 5px 7px; border: 1px solid #dde8df; font-size: 9.5px; }
    tr:nth-child(even) td { background: #f6faf7; }
    .footer { margin-top: 14px; font-size: 8.5px; color: #5a7a60; }
</style>
</head>
<body>
<h1>ISAMS — {{ $title }}</h1>
<div class="sub">Saint Columban College &middot; Pagadian City &middot; Generated {{ now()->format('M d, Y h:i A') }} &middot; {{ count($rows) }} record(s)</div>
<div class="rule"></div>
<table>
    <thead><tr>
        @foreach($headings as $h)<th>{{ $h }}</th>@endforeach
    </tr></thead>
    <tbody>
    @forelse($rows as $row)
        <tr>@foreach($row as $cell)<td>{{ $cell }}</td>@endforeach</tr>
    @empty
        <tr><td colspan="{{ count($headings) }}" style="text-align:center;padding:16px;color:#5a7a60;">No records found.</td></tr>
    @endforelse
    </tbody>
</table>
<div class="footer">Generated by ISAMS — Integrated Student Affairs Management System</div>
</body>
</html>
